=== Manav311/augentix-/library/libcm/codegen/schema/agtx_iva_eaif_conf.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"type": "object",
	"title": "AGTX_IVA_EAIF_CONF_S",
	"properties": {
		"enabled": {
			"type": "boolean",
			"ui_type": "boolean",
			"ui_access_right": "read_write"
		},
		"obj_life_th": {
			"type": "integer",
			"ui_type":"number",
			"ui_access_right": "read_write"
		},
		"video_chn_idx": {
			"type": "integer",
			"ui_type":"number",
			"ui_access_right": "read_write",
			"default": 0,
			"minValue": 0,
			"maxValue": 3
		},
		"target_idx": {
			"type": "integer",
			"ui_type":"number",
			"ui_access_right": "read_write",
			"default": 0
		},
		"snapshot_width": {
			"type": "integer",
			"ui_type":"number",
			"ui_access_right": "read_write",
			"description": "snapshot width (classification only)",
			"default": 1920
		},
		"snapshot_height": {
			"type": "integer",
			"ui_type":"number",
			"ui_access_right": "read_write",
			"description": "snapshot height (classification only)",
			"default": 1080
		},
		"api": {
			"type": "string",
			"title": "AGTX_IVA_EAIF_API_METHOD_E",
			"enum": ["FACEDET", "FACERECO", "DETECT", "CLASSIFY", "CLASSIFY_CV", "HUMAN_CLASSIFY"]
		},
		"classify_model":{
			"type": "string",
			"description": "classify model name from host server",
			"maxLength": 256
		},
		"classify_cv_model":{
			"type": "string",
			"description": "classify cv model name from host server",
			"maxLength": 256
		},
		"detect_model":{
			"type": "string",
			"description": "detect model name from host server",
			"maxLength": 256
		},
		"face_detect_model":{
			"type": "string",
			"description": "face detect model name from host server",
			"maxLength": 256
		},
		"face_reco_model":{
			"type": "string",
			"description": "face reco model name from host server",
			"maxLength": 256
		},
		"human_classify_model":{
			"type": "string",
			"description": "human classification model name from host server",
			"maxLength": 256
		},
		"data_fmt": {
			"type": "string",
			"title": "AGTX_IVA_EAIF_DATA_FMT_E",
			"enum": ["JPEG", "Y", "YUV", "RGB", "MPI_JPEG", "MPI_Y", "MPI_YUV", "MPI_RGB"]
		},
		"url": {
			"type": "string",
			"maxLength": 256
		},
		"pos_stop_count_th": {
			"type": "integer",
			"description": "Threshold to stop sending request when one object accumulated same positive result"
		},
		"pos_classify_period": {
			"type": "integer",
			"description": "Period to send request for an object with positive result(# frames)"
		},
		"neg_classify_period": {
			"type": "integer",
			"description": "Period to send request for an object with negative result(# frames)"
		},
		"detection_period": {
			"type": "integer",
			"description": "Period for object detection (# frames)"
		},
		"identification_period": {
			"type": "integer",
			"description": "Period for identification detection (# frames)"
		},
		"min_size": {
			"type": "integer",
			"description": "Minimum face size (pixel) for identification"
		},
		"inf_with_obj_list": {
			"type": "integer",
			"description": "Enable object list based model inference (for detection only)"
		},
		"obj_exist_classify_period": {
			"type": "integer",
			"description": "Period to send request for any positive object exists on the screen (# frames)"
		},
		"inf_cmd": {
			"type": "string",
			"title": "AGTX_IVA_EAIF_INF_CMD_E",
			"enum": ["NONE", "FACE_REGISTER", "FACE_LOAD", "FACE_SAVE", "FACE_DELETE", "FACE_RESET"],
			"description": "inference command"
		},
		"face_name": {
			"type": "string",
			"maxLength": 256
		},
		"facereco_roi_sx": {
			"type": "integer",
			"minValue": 0,
			"maxValue": 99
		},
		"facereco_roi_sy": {
			"type": "integer",
			"minValue": 0,
			"maxValue": 99
		},
		"facereco_roi_ex": {
			"type": "integer",
			"minValue": 1,
			"maxValue": 100
		},
		"facereco_roi_ey": {
			"type": "integer",
			"minValue": 1,
			"maxValue": 100
		}
	}
}

=== Manav311/augentix-/application/sample/eai_hd_demo/assets/hd_conf_inapp.json
{
    "obj_life_th": 8,
    "target_idx": 0,
    "api": "HUMAN_CLASSIFY",
    "data_fmt": "MPI_Y",
    "url": "inapp",
    "snapshot_width": 640,
    "snapshot_height": 360,
    "pos_stop_count_th": 99,
    "pos_classify_period": 50,
    "neg_classify_period": 10,
    "obj_exist_classify_period": 0,
    "face_reco_model": "whatever",
    "detect_model": "whatever",
    "classify_model": "whatever",
    "classify_cv_model": "whatever",
    "human_classify_model": "/system/eaif/models/classifiers/shuffleNetV2/inapp.ini"
}

=== Manav311/augentix-/application/sample/hd_demo/assets/hd_conf_remote.json
{
    "obj_life_th": 16,
    "target_idx": 0,
    "api": "HUMAN_CLASSIFY",
    "data_fmt": "MPI_Y",
    "url": "http://127.0.0.1:8164",
    "snapshot_width": 640,
    "snapshot_height": 360,
    "pos_stop_count_th": 3,
    "pos_classify_period": 100,
    "neg_classify_period": 25,
    "face_reco_model": "whatever",
    "detect_model": "whatever",
    "classify_model": "whatever",
    "classify_cv_model": "whatever",
    "human_classify_model": "shuffleNetV2"
}

=== Manav311/augentix-/sample/hd_demo/assets/hd_pet.json
{
    "obj_life_th": 8,
    "target_idx": 0,
    "api": "HUMAN_CLASSIFY",
    "data_fmt": "MPI_RGB",
    "url": "inapp",
    "snapshot_width": 12780,
    "snapshot_height": 720,
    "pos_stop_count_th": 99,
    "pos_classify_period": 50,
    "neg_classify_period": 5,
    "obj_exist_classify_period": 0,
    "face_reco_model": "whatever",
    "detect_model": "whatever",
    "classify_model": "whatever",
    "classify_cv_model": "whatever",
    "human_classify_model": "/system/eaif/models/oc/pet.ini"
}
